import "./globals.css";
import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";

const hgFont = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={hgFont.className}>{children}</body>
    </html>
  );
}
